version: '3.8'

services:
  webapi:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    ports:
      - "5000:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapi
