FROM bitnami/kubectl:1.27.3 AS kubectl

FROM line/kubectl-kustomize:1.27.3-5.1.0 AS kustomize

FROM docker:20.10.24

COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/

COPY --from=kustomize /usr/local/bin/kustomize /usr/local/bin/

RUN apk update && apk add --no-cache curl bash gettext jq sudo htop yq git sudo
