version: "3.9"

services:
  petclinic:
    build: .
    restart: always
    ports:
      - "9000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default,mysql
      - MYSQL_URL=jdbc:mysql://petclinicdb/${db_schema}
      - MYSQL_USER=${db_user}
      - MYSQL_PASS=${db_password}
    depends_on:
      petclinicdb:
        condition: service_healthy


  petclinicdb:
    container_name: database
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password # just needed for root user
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}
      - MYSQL_DATABASE=${db_schema}
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u${db_user} -p${db_password}
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s


  # username = petclinic
  # password = petclinic
  # db = petclinic
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: petclinicdb
    ports:
      - "8080:8080"
    depends_on:
      petclinicdb:
        condition: service_healthy
